### ISSUE TITLE
About page: Logos for ESRC and British Academy are not appearing correctly

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#100]
ESRC and BA logos are not appearing correctly on the About page, as below:
![image](https://user-images.githubusercontent.com/36402489/37371516-80091c56-2707-11e8-8e57-0dbc7e4f123b.png)

**Comment by paluchas** [comment]
@RKasprowicz I can't replicate this bug? I'm testing production.

**Comment by paluchas** [comment]
@RKasprowicz This is down to copy/paste operation preserving the original URL location of the images. I have updated the production about page with images as shown on the production home page. This should render correctly now.
