### ISSUE TITLE
Admin access to production site

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#101]
Please can Rowena, Sophie, and Emma be given admin access to the production site?

**Comment by paluchas** [comment]
@RKasprowicz I have added you and Emma to admin roles. 

@SophieThompson can you sign in to the production system. I'll be able then to add your email to admin roles too.

**Comment by SophieThompson** [comment]
@RKasprowicz yes, have done.

**Comment by paluchas** [comment]
@SophieThompson @RKasprowicz I have added iris email to admin users.
