### ISSUE TITLE
Upload summary tab missing

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#107]
On the demo site, the tab button for "Upload summary" is missing:
![image](https://user-images.githubusercontent.com/36402489/37514223-3588c4e8-28ff-11e8-96ba-937a45903b93.png)

On the production site, the "Upload summary" tab is still visible, but clicking on it brings up this error message:
![image](https://user-images.githubusercontent.com/36402489/37514175-15d922b4-28ff-11e8-806e-022cd1d8befd.png)

**Comment by RKasprowicz** [comment]
@yf508 @paluchas When I log into the demo site, I can see the upload summary tab at it takes me to the upload form - so that seems to be working. 
But I still get an error message when I click on the Upload summary tab on the production site.

**Comment by RKasprowicz** [comment]
@yf508 @paluchas I've just tested this again and the production site now seems to be working --> the upload tab takes me to the upload form.

**Comment by yf508** [comment]
@RKasprowicz yes, it has been fixed.
