### ISSUE TITLE
Production site: Error message when try to download summary or edit summary metadata

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#111]
On the **production** site:
I can see the entry for the summary that Sebastian created, however I found 2 errors:

1) when I click "download pdf", the following error message is given:
![image](https://user-images.githubusercontent.com/36402489/37571755-b2de5124-2af8-11e8-8ea3-eac33731d3e8.png)

2) when I click "edit" to edit the summary metadata, I get an error message:
![image](https://user-images.githubusercontent.com/36402489/37571760-d164c0b0-2af8-11e8-8853-7757bd77ddb3.png)

**Comment by paluchas** [comment]
This is the same cause as for #112 (unavailable Fedora). It is resolved now.
