### ISSUE TITLE
File not uploading first time

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#115]
@paluchas @RKasprowicz FYI

When I save description and file after completing all the fields I get the following screen with no thumbnail showing (and as far as I can tell no file attached). I have to go to edit to re-attach the file and then it appears fine. This has happened the last few times.

![image](https://user-images.githubusercontent.com/36706240/37673769-fcb9910c-2c68-11e8-941a-f8c686918d3d.png)

**Comment by SophieThompson** [comment]
to update, it seems actually the file is there (I can download it) but the thumbnail isn't showing.

**Comment by paluchas** [comment]
I've spot this too. It is investigate now. In the similar circumstances do
not attempt to upload file again. This will only create additional copy of
the file but will not solve the thumbnail issue.

**Comment by SophieThompson** [comment]
Yes, sorry, I realised this too late. although I think some multiples are no my doing, e.g. one of the records has 6 files! I'm sorry I've not had chance to delete all the multiples yet but I'll try to as soon as I can. Thanks for investigating. Apart from this uploading has worked really well!

**Comment by paluchas** [comment]
The record shows correctly now.

I have removed additional files and refreshed metadata about the summary record. This was a process of using the web interface (remove files) and rails console (refresh default file and thumbnails ids).
