### ISSUE TITLE
Adding new items to fields

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#116]
This is just a question, apologies if I should know the answer.
How in the future will we add new items to the fields in the upload form? For instance, I need to add a new journal name (International Journal of Bilingualism).
Thanks.

**Comment by RKasprowicz** [comment]
We also need to add the journals: 

- Computer Assisted Language Learning 
- Journal of Second Language Pronunciation
- ReCALL

**Comment by yf508** [comment]
Closed as it is fully covered by #126
