### ISSUE TITLE
Upload form / search category: Create new metadata fields "Country / region" [multiple choice], "Subnational region e.g. state / countries within the UK" [free text], "Educational stage" [multiple choice], "Institutional characteristics" [multiple choice]

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#121]
Please create new (multiple choice) metadata fields for "Country" [multiple choice], "Subnational region e.g. state" [free text], "Educational stage" [multiple choice], "Institutional characteristics" [multiple choice].

If possible, US states should appear when United States is selected in the "Country" list. If this is a lot of work, it is not that important.

New fields and terms are listed in the [Updated_OASIS Search Terms spreadsheet](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing)

The [Metadata fields ](https://docs.google.com/spreadsheets/d/1PsDwATtIqQFYDr9b16LxeAlJnr-ggFVokCyuvZOPQ_I/edit?usp=sharing )spreadsheet lists the requirements for these fields.

This field should appear of the upload form, and also as a searchable facet on the search results page

**Comment by paluchas** [comment]
See this link with some [countries list](https://data.europa.eu/euodp/data/dataset/country)

**Comment by paluchas** [comment]
@yf508 Might be of interest during implementation. Carmen [gem](https://github.com/carmen-ruby/carmen) offers a clean API for countries and regions.
