### ISSUE TITLE
Upload form: Free text entry box for term "Other" in all multiple choice metadata fields

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#122]
All multiple choice metadata fields include the term "Other". When a user selects "other", a free text entry box should be displayed where the user can enter a term. This term will not appear in the search facets, however will appear on the detailed summary view for the summary in question.

**Comment by yf508** [comment]
This requires changes to the model, e.g. add a field to store the text while 'other' being clicked. The new fields need to be searchable, but not facetable.

**Comment by paluchas** [comment]
@yf508 this should be implemented in the way that Other is an independent text box that shows once a user is selecting "other" form the term list

**Comment by RKasprowicz** [comment]
@yf508 Ok, this is fine. So, when the user selects "other" in the term list, a text box will appear. When a user enters a term in the box, a new box will appear, so that they have the option to enter another term.

These terms will be searchable but not facetable (i.e. it won't appear in the search lists). In the summary detailed view page, the word "other" will not appear in the metadata, only the term entered in the ("other") text box will appear. Multiple terms will be separated by a semicolon ( ; ) 

Managing new terms - what happens to them? How will OASIS administrators review terms entered under "other"? As an admin, I would like to see a list, on a regular basis, of all terms entered under "Other" for each multiple choice metadata field, and which summary that term has been used for.

**Comment by paluchas** [comment]
@yf508 I think full-text search is not working with new other fields. Can you have a look at this, please?

**Comment by yf508** [comment]
Re: how to see a list of 'other' items?

Just use the facet. Although the actual texts for 'other' fields are not facetable, the  text 'other' itself is in the facet, which can be clicked to give a list of all records containing 'other' texts.

![image](https://user-images.githubusercontent.com/437701/43466026-88ae9542-94d6-11e8-9f10-37d440ef33df.png)

**Comment by IAlferink** [comment]
Feature works fine for 'topic' and 'journal of publication', but when I click the 'other' option for the following topics no text box appears:
- Language summary written in
- Participant type
- Of likely interest to

<img width="776" alt="screen shot 2018-08-01 at 09 53 07" src="https://user-images.githubusercontent.com/40735172/43511616-bdd1524c-9570-11e8-9618-8faeeb30e365.png">

**Comment by RKasprowicz** [comment]
@yf508 @IAlferink Yes, please include Other in all of those fields.

Note: for First Language of Learners and Language Being Learned, is it possible for these fields to be populated with a 'standard' language list (as IRIS is)? (see #79 )

**Comment by IAlferink** [comment]
@yf508 Reposting Rowena's question: for First Language of Learners and Language Being Learned, is it possible for these fields to be populated with a 'standard' language list (as IRIS is)? (see #79 )

**Comment by yf508** [comment]
@RKasprowicz @IAlferink that's been done, language lists have been updated from IRIS.

**Comment by IAlferink** [comment]
@yf508 Great! Thanks
