### ISSUE TITLE
Upload form / search facet: Missing terms to be added to metadata fields "Journal of Publication", "Topic" and "Proficiency of learners"

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#126]
List of terms under "Journal of Publication" needs to be updated.

20 titles need to be **added** (listed below and indicated in yellow on [Updated_OASIS Search terms spreadsheet](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing) in the column "Journal of Publication").

14 titles need to be **removed** (listed below and indicated in red on [Updated_OASIS Search terms spreadsheet](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing) in the column "Journal of Publication").

**Titles to be added (20):**
- Applied Linguistics Review
- Computer Assisted Language Learning
- English for Specific Purposes
- Intercultural Pragmatics
- International Journal of Bilingualism
- Journal of Communication Disorders
- Journal of French Language Studies
- Journal of Second Language Pronunciation
- Language Culture and Curriculum
- Language Teaching
- Language and Intercultural Communication
- Literacy
- Metaphor and Symbol
- Multilingua - Journal of Cross-Cultural and Interlanguage Communication
- Porta Linguarum
- Pragmatics and Society
- ReCALL
- Revista Española de Lingüística Aplicada /Spanish Journal of Applied Linguistics
- Vial-Vigo International Journal of Applied Linguistics
- World Englishes

**Titles to be removed (1):**
- Dutch Journal of Applied Linguistics
- Frontiers: The Interdisciplinary Journal of Study Abroad
- Innovation in Language Learning and Teaching
- International Journal of Applied Linguistics
- International Journal of Speech Technology
- Journal of Educational and Social Research
- Journal of Immersion and Content-Based Language Education
- Reading in a Foreign Language
- Studies in Second Language Learning and Teaching
- TESL-EJ
- TESOL Canada Journal
- TESOL in Context
- The Language Learning Journal
- The Quarterly Journal of Experimental Psychology

Links to issue #116

**Comment by paluchas** [comment]
It should be relatively "straightforward" to add a new journals titles to the system, however, any changes to the controlled list will have a profound implication of the existing summaries e.g. we will require to update each of them to reflect the introduced change. Basically, adding a new entry will change existing IDs of current Journal Titles as we store them in alphabetical order so adding a new Title stating with A will shift all other entries to new position IDs+1. In consequence, all existing will require changes in stored metadata. This could be very complex and complicated process. 

Unfortunately, this is a shortcoming of our data modelling as we have not planned ahead this possibility. I need to catch up with @yf508 to understand this in more details.

**Comment by yf508** [comment]
(**This applies to all authority terms**) The order of journals in the form is determined by the order of journals in the authorities list file, not by IDs.

To add a new journal name, we need to update the authority file, making sure the new journal name is added in the appropriate position to maintain the alphabetical order of the term, and allocating a new unique ID for the new journal. 

While deleting a journal, to avoid data corruption, first we need to check if the journal is referenced by any summary before deleting it.

**Comment by paluchas** [comment]
@yf508 Thanks for clarifying this.

@RKasprowicz how often do you expect you would require updating the journal title list? Would you expect to update other authority lists too?

**Comment by RKasprowicz** [comment]
@paluchas @yf508 Thank you both for the information about this. I have checked with Emma and we have decided that it would be best to wait to update the journal list until after our meeting on 24th May (because, as you mentioned Sebastian, changing the authority list will corrupt existing records, and the existing records are being used at the moment). So please **do not** update the journal list for now.

@paluchas In relation to your questions, yes we will need to be able to update the authority lists for all of the multiple choice metadata lists. These changes will not happen often, but we do need to be able to add a term to a list, as necessary. Is it possible to have a similar model to IRIS - i.e. the OASIS admin has access to the data dictionary of all terms in each metadata field and can add a term when necessary.  This is because, occasionally, OASIS uploaders may select "Other" and specify a term that is not currently listed under that metadata field (see issue #122 ).  The OASIS admin can then periodically review the terms given under "Other" and decide which terms (if any) should be added to the main list of terms for that metadata field.

**Comment by paluchas** [comment]
@RKasprowicz thanks for explaining a bigger context re frequency of term updates. 

I think @Frank has found a solution to update the term lists based on the backend process. However, this was not widely tested yet.  Regarding an admin being able to add new terms as required, this should be documented and prioritised among other requests. We can discuss this at the forthcoming meeting.

**Comment by RKasprowicz** [comment]
For the proficiency of learners field, one term needs to be updated (in yellow in the Updated_Search Terms spreadsheet). This term was previously spelt wrong and needs to be corrected.

Incorrect spelling: CFER. Correct spelling: CEFR

**Comment by paluchas** [comment]
We require extending[ this rake task](https://github.com/digital-york/oasis/blob/update_authorities/lib/tasks/authorities.rake) to cover all authorities.

**Comment by paluchas** [comment]
**Questions**: Should this be implemented before or after #1

**Comment by RKasprowicz** [comment]
@paluchas The terms to be added in these fields are all top level terms, so they can be added before #1 is implemented.

**Comment by RKasprowicz** [comment]
@paluchas @yf508 There are three fields that need terms adding Journal

**Comment by RKasprowicz** [comment]
@yf508 I have added one more Journal title to the list in the description box above to be added to OASIS (Journal of Second Language Pronunciation)

**Comment by yf508** [comment]
Intructions here: https://github.com/digital-york/oasis/wiki/How-to-manage-terms-(authorities)---For-OASIS-admin-and-technical-people
