### ISSUE TITLE
Add licence information to "Summary details" view

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#145]
## Context
A user should be able to see what condition summary can be downloaded and used. We are collecting licence information in deposit interface, however, this is not shown in the detailed page view.

## Proposed solution
Add a simple metadata entry to "Summary details" main section. This should appear after "Of likely interest to...". The entry should include License (what spelling ? US/UK) following text to Licence wording and a clickable link to cc web site. For example

**License** Attribution-NonCommercial-ShareAlike 4.0 International ([CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/))

In addition, we might want to consider adding a licence abbreviation at **How to cite this summary** page section. For example,

```
CC BY-NC-SA 4.0 Said, F. & Melo-Pfeifer, S. (2018). The role of the family in the learning and use of the heritage language from the point of view of children. OASIS Summary. https://oasis-database.org/concern/summaries/2z10wq20d?locale=en
```

**Comment by em502** [comment]
@paluchas 
For now, please could 
1) the Copyright © 2018 OASIS be removed from the bottom right of the home screen
2) Replace that with the following: All summaries held on OASIS have a Creative Commons License Attribution-NonCommercial-ShareAlike 4.0 International ([CC BY-NC-SA 4.0]
with the embedded link (https://creativecommons.org/licenses/by-nc-sa/4.0/))

Once we are 100% sure whether that is the right licence (I need to check with some publishers this serves their wishes well), then we can think about putting it 
a) on the summaries themselves (not in front of the citation as you suggest, but another way, yes)
and / or b) alongside the metadata on the results pages, where people download. **Exactly** as you suggest in the proposed solution

please could you confirm this is ok? 
Emma

**Comment by paluchas** [comment]
@em502 I have mocked up the suggested change, see attached image. The text seems to be a little bit lengthy. Maybe we can just say 

"All summaries are licensed as CC BY-NC-SA 4.0" 

with the embedded link https://creativecommons.org/licenses/by-nc-sa/4.0/

<img width="1272" alt="screen shot 2018-05-16 at 16 19 21" src="https://user-images.githubusercontent.com/1863245/40126715-d0911cdc-5925-11e8-941e-9456369c5ae0.png">

**Comment by paluchas** [comment]
As adviced by colleagues form research support team we could use PLOS OA icon that is CC0. Here is a [link to the icon](https://commons.wikimedia.org/wiki/File:Open_Access_logo_PLoS_transparent.svg).

**Comment by em502** [comment]
that's brilliant
 thank you!

Dr Emma Marsden,
<http://www.york.ac.uk/education/our-staff/academic/emma-marsden/> Director
of Research, Dept. of Education, Univ. of York, UK

*Language Learning*
<http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-9922> (Associate
Editor)

*Instruments for Research into Second Languages (IRIS
<http://www.iris-database.org/>) *

*Open Accessible Summaries of Research in Language Studies (OASIS
<https://oasis-database.org/>)*

*New articles:*

Replication in second language research: Narrative and systematic reviews,
and recommendations for the field
<http://onlinelibrary.wiley.com/doi/10.1111/lang.12286/epdf> *Language
Learning.*

Introducing Registered Reports at Language Learning: Promoting
Transparency, Replication, and a Synthetic Ethic in the Language Sciences.
<http://onlinelibrary.wiley.com/doi/10.1111/lang.12284/full>*Language
Learning. *

Practitioner exposure to research and a call for action
<http://onlinelibrary.wiley.com/doi/10.1111/modl.12426/epdf>, *The Modern
Language Journal.*

Towards ecological validity in research into input-based practice
<https://doi.org/10.1093/applin/amw051>*. Applied Linguistics.*

A methodological synthesis of self-paced reading in second language
research (accepted). *Applied Psycholinguistics.*

**Comment by RKasprowicz** [comment]
All summaries will be published under CC-BY-NC-SA licence. This information / appropriate licence icons should be presented on the summary detailed view page under the section "How to cite this summary".

**Comment by paluchas** [comment]
Related to #154. We need to add information about the licence in the summary detailed page. I suggested adding a [CC-BY-NC-SA icon](https://creativecommons.org/about/downloads/) in the top section (title) as well as add a wording about the licence in How to cite this summary field.

**Comment by RKasprowicz** [comment]
@yf508 I think this is ok, but will need to confirm with Emma that she is happy with this.

One question: Is it possible for a user to click on the icon, and be taken to the licence webpage which explains what the licence means, i.e. https://creativecommons.org/licenses/by-nc-sa/4.0/ 
If this is not implemented, please can this be added (clicking on the icon to go to the licencing web page). 

@IAlferink When you next meet/ speak to Emma, please could you confirm that she is happy with the layout that Frank has provided above?

**Comment by IAlferink** [comment]
@RKasprowicz @yf508 I'll check with Emma that she's happy with this once she's back from leave.

**Comment by em502** [comment]
Thanks all

In case Frank needs me to confirm, I am chipping in here (but, for info,
won't look again at email for a good few days).

Looks ok!!

One thing, please could the publication reference link to the journal
homepage (preferably where the issue is held but this might not be possible
as it will first be on the EarlyView/FirstView) then moved to the actual
issue. And that move won't happen until after the summary is posted. So...
probably just link to the journal homepage. The link from the journal title
in the reference?

For now we have a finite set of about 12 journals. It won't grow to more
than about 20 max 30.

Rowena, Inge, I leave this with you now. It may be too complicated.

(The underpinning thinking=
Inside the summaries we will also have a link to the journals  (so 2
links). I think it's important for convincing journals it's a win win. They
get increased visibility for their journal and the authors get visibility
for their article. Readers get an easy link to original if they want it.)

With many thanks again.
Looking good!
E

**Comment by yf508** [comment]
Thanks all for the feedback.

Re: @RKasprowicz the link to BY-NC-SA is already in place. 

Re: @em502 The required feature is possible. The current authority list doesn't contain the links. We'd better to create a new issue for it.
