### ISSUE TITLE
Implement correct workflow / process for summaries to be released (made public)

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#151]
An uploader cannot make summary public on upload. 

On upload, the uploader will select "submit for approval" (or similar, under visibility options) and save the record.

The OASIS admin (oasis@oasis-database.org) will be notified that a new summary has been uploaded.

The OASIS admin will view the summary and then make the summary public.

**Comment by paluchas** [comment]
related to #152

**Comment by yf508** [comment]
Here is the basic instructions on how to use mediated workflow:

https://docs.google.com/document/d/1g9dnq7cLXqFqWEBiQjZRNEe63EeISe3dSYxPjTP676I/edit#

**Comment by IAlferink** [comment]
@RKasprowicz Question for you. Currently, a depositor receives an email when an administrator uses the 'request change' or 'comment' options, but not when they use 'approve'. I think it would be useful for the depositor also to be notified when their summary is approved. What do you think?

**Comment by IAlferink** [comment]
@yf508 I'm not getting a notification on the dashboard when there's just a comment on the pending summary. Notification does work for 'request changes' and 'approve'.

**Comment by yf508** [comment]
Thanks for testing this feature @IAlferink . I think that's the expected Hyrax behavior. If you think the notifications for comment are import, pls create a GH issue and we will have a look later.

**Comment by IAlferink** [comment]
@yf508 A couple of points::
1) When I go to the summary details page to review and approve a summary I can't see / click on the pdf.

2) As an admin I'm not getting a notification for a new submission. The submission does appear in the Submissions to review list.

3) As an uploader I'm getting a dashboard notification of any requests and approvals, but no email. Your workflow document says there should be: https://docs.google.com/document/d/1g9dnq7cLXqFqWEBiQjZRNEe63EeISe3dSYxPjTP676I/edit

**Comment by IAlferink** [comment]
@RKasprowicz @Em502 I could use an extra pair of eyes on this issue. The workflow seems fairly transparent for submissions that get approved immediately. However, when changes are requested I find the procedure not particularly intuitive. I think we need some explanations somewhere. I've tried illustrate the procedure here: https://docs.google.com/document/d/1T1hT826WHofvtqYnEy9J9c7M-DylDacHB-8sCJWRe9M/edit?usp=sharing

Any ideas how to make it more clear to uploaders on the website?

**Comment by IAlferink** [comment]
@yf508 @yf508 There are some questions and comments in this doc as well. Could you please have a look? See also previous comment
https://docs.google.com/document/d/1T1hT826WHofvtqYnEy9J9c7M-DylDacHB-8sCJWRe9M/edit?usp=sharing

**Comment by IAlferink** [comment]
@yf508 @RKasprowicz I now see that the emails to the uploader did come through. It just took some hours before they did.
