### ISSUE TITLE
Upload form: Uploader should only have one licence option (CC-BY-NC-SA) on the upload form when uploading a summary

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#154]
Second licence option (CC-BY-NC) should be removed from the upload form (and the description text adjusted accordingly).

User should still have to tick / select CC-BY-NC-SA on the upload form (even though it is the only option)

**Comment by paluchas** [comment]
All existing and future summaries will have licence [CC-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).
