### ISSUE TITLE
Terms and conditions statement to be added to the sign-up page, under the sign-up boxes

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#156]
Terms and conditions statement needs to be added to the sign-up page, to tell user that they will be asked 
whether they would like to receive alerts for the summaries they upload. And also to tell them that they can unsubscribe from the alerts whenever they want to by contacting OASIS.

**Comment by RKasprowicz** [comment]
@volhar

**Comment by yf508** [comment]
**I think** this feature (individual user-based alert settings) is not available in the underlying framework (Hyrax). Could you please provide me with the sign-up page texts and I will get it updated?

**Comment by IAlferink** [comment]
@RKasprowicz @yf508 Clarification question: Is this for the sign up page or the upload page? In the meeting notes it refers to sign in / upload. Where exactly will users be asked whether they want to receive alerts? Related, should we also add a sentence to the 'receive notification for downloads' option. In case someone wants to unsubscribe from those?

**Comment by RKasprowicz** [comment]
@yf508 @paluchas for info

@IAlferink Currently, the functionality for users receiving alerts is not in place, so I am not sure when / how users would opt-in to this. We will have to come back to this, once we have an outline for how alerts might function in the system.

However, users will need to sign-up (register email and create password) on the OASIS web page in order to upload summaries. So on the sign-up page, there should be a sentence saying that users' email addresses will be stored by OASIS and will only be used in relation to the summary(ies) being uploaded and that users can unsubscribe from the website by contacting the OASIS team (provide email address).

Similarly, on the upload form, where it asks the user to provide an email address, a sentence needs to be added saying that users' can unsubscribe from the website by contacting the OASIS team (provide email address). And yes, also on the notification of download question.

At a later date, once the functionality for summary alerts (i.e. alert me when a summary about X is uploaded) has been worked out, we can add a sentence for that.

**Comment by RKasprowicz** [comment]
@yf508 Re. your comment above about alerts - is the functionality in place for users to receive alerts when their summary is downloaded? (as happens on IRIS)?

**Comment by IAlferink** [comment]
@yf508 Ok, that makes sense. Thanks for the clarification.

**Comment by IAlferink** [comment]
@yf508 Here is the language for the sign up page and download notifications:
https://docs.google.com/document/d/11EfvnxLf7CFlBTc2aUZPlcyWOD1SnUzjTzud6bJ8TAE/edit?usp=sharing

@RKasprowicz Could you quickly look it over too?

**Comment by yf508** [comment]
I don't think we provide individual notification services, e.g. individuals cannot subscribe / unsubscribe to notifications. **I think** the current implementation only support a global setting for all users, e.g. if we enable/disable notifications, then all registered users will/won't receive notifications.

You may want to rephrase the texts? @IAlferink @RKasprowicz

**Comment by IAlferink** [comment]
@yf508 Ok, but then why are people asked to indicate whether they want to receive notifications of downloads?
<img width="608" alt="screen shot 2018-08-07 at 10 13 11" src="https://user-images.githubusercontent.com/40735172/43766521-8af723d8-9a2a-11e8-811c-3a367bb3fe1e.png">

**Comment by yf508** [comment]
Good question, this field is copied from IRIS. We should remove it for now. @IAlferink 

What do you think? @RKasprowicz

**Comment by IAlferink** [comment]
I just want to clarify something, because I feel we're really talking about three different things:

1) People need to leave their email so we can contact them if anything goes wrong with their submission as part of the sign up process. Can we remove these if people ask us to?

2) Sending alerts of downloads of their work -- Frank indicates this is not possible on the individual level. We should remove the option.

3) Sending alerts of new summaries being uploaded. Is this possible at all or not? If it is I assume also only on a blanket setting?
@yf508 

FYI @RKasprowicz @Em502

**Comment by em502** [comment]
Thank you very much for raising these issues Inge

2/ I would really like this to be possible - is it out if the question

3/ alerts- I really hope that at some stage we can allow people to ask for
bespoke alerts (e.g. "i'd like to know if any summaries are uploaded in the
area of [tagged with] "grammar learning" or "young learners"").
So for now I appreciate the alerts might need to be "blanket" I.e. you get
an alert every time any new summary is uploaded, but eventually it will be
nice to have these for specific keywords only.

On our way home later today

Emma

**Comment by yf508** [comment]
Just to clarify:

Technically individual notifications are possible. Just the underlying component we are using does not support that feature at present. If we want to build it our own, it is another major task for OASIS and it goes too far from core components we are using which may cause some problems when we upgrade those components in the future.

Re 3) Currently, new summaries alerts go to admin's email/notifications. It's also a global settings.

**Comment by IAlferink** [comment]
@em502 Blanket as in: everybody gets them or nobody gets them. Essentially this means that you wouldn't be able to unsubscribe which would be undesirable (illegal even?). If I understand this correctly.

**Comment by IAlferink** [comment]
@yf508 Thanks for the clarification. So, as far as notifications for downloads or new uploads (for depositors) go it's technically possible, but a major task. 

Can you confirm number 1) is possible?
1) People need to leave their email so we can contact them if anything goes wrong with their submission as part of the sign up process. Can we remove these if people ask us to?

**Comment by yf508** [comment]
Not sure what you mean 'these' in the question.

We can remove an account, but cannot just delete email and keep their account.

**Comment by yf508** [comment]
@IAlferink 
1) Yes
2) We **should** be able to do that.

**Comment by IAlferink** [comment]
@yf508 Thanks

**Comment by IAlferink** [comment]
@yf508 I've updated the language to reflect our discussions here:
https://docs.google.com/document/d/11EfvnxLf7CFlBTc2aUZPlcyWOD1SnUzjTzud6bJ8TAE/edit?usp=sharing

**Comment by em502** [comment]
IN CAPS BELOW

On Tue, 7 Aug 2018, 11:57 am Frank Feng, <notifications@github.com> wrote:

> Just to clarify:
>
> Technically individual notifications are possible. Just the underlying
> component we are using does not support that feature at present. If we want
> to build it our own, it is another major task for OASIS and it goes too far
> from core components we are using which may cause some problems when we
> upgrade those components in the future.
>
1/ PLEASE COULD YOU GIVE AN ESTIMATE OF HOW LONG THESE WOULD TAKE?
A) INDIVIDUALS BEING ABLE TO SELECT "ALERT ME FOR EVERY NEW SUMMARY"
B)  INDIVIDUALS BEING ABLE TO SELECT "ALERT ME FOR EVERY NEW SUMMARY
RELATED TO "KEY WORD X"

2/ PLEASE COULD YOU CLARIFY WHAT WILL BE POSSIBLE AT THE END OF THIS
SPRINT? Is it the blanket alerts Inge referred to? I.e.either everyone who
has given their email or none of them?

> Re 3) Currently, new summaries alerts go to admin's email/notifications.
> It's also a global settings.
>

I DON'T UNDERSTAND "GLOBAL SETTINGS"? DOES THIS MEAN WE COYLD CHOOSE FOR
OTHERS (NON-ADMIN) TO SELECT IT?

*Inge -  If ONLY admin can get alerts, I wonder if we can set up something
that the OASIS admin can operate until it can be done automatically? Like
could we keep an excel list of key words with emails of those who want
summaries with those key words and use "yetanothermailmerge" to send them
automatically? Seems clunky...but you might think of something?

As you can see... :-)  I'm quite keen on this functionality , particulary
given the exchange the other day with Florence Myles-  their teacher
network is a good example of why this is important (I think you were cced
into some of that). I do appreciate it's complex but I'm just putting this
down as a marker now,  so we know for later development sprints

All for now
E

**Comment by IAlferink** [comment]
@em502 Yes, this functionality seems pretty vital to keeping users engaged with the database. I'll explore some temporary options.

**Comment by em502** [comment]
i interpret this as meaning:
"yes, we can remove an account i.e. delete someone's email and the
summaries that they are linked to and any other information e.g. their
institution and any download stats on their account
"
and "yes, we can keep their summaries on OASIS"

if i've got this wrong, please let me know, as this IS what we would like
to happen (=be able to remove someone's email address - and therefore,
their associated account-  but keep the summaries!)

thanks
Emma

**Comment by yf508** [comment]
@em502 

We don't store user's institution information, also the download stats is not supported in current OASIS. Therefore, we can delete user's OASIS account (including email) but keep their summaries in OASIS.

**Comment by yf508** [comment]
A separate issue should be created if the customized notifications are required.

**Comment by IAlferink** [comment]
@yf508 One tiny change. There should be a space after account (see arrow):
<img width="1149" alt="screen shot 2018-08-09 at 17 02 36" src="https://user-images.githubusercontent.com/40735172/43911047-55b36c2c-9bf6-11e8-8328-dfeb364e97fb.png">
