### ISSUE TITLE
Update facet fields

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#16]
Specific requests form OASIS team: 

- Research Area
- Authors of the Research (i.e from the "references" field, i.e. the authors of the study being summarised, not the person who uploaded the summary)
- Year the Research Published (i.e. from the "references" field, i.e. when the study was carried out)
- Date the Summary was Uploaded
- Writer of the Summary (the person who wrote the summary, which will include the authors of the research)
- Language Being Learned

**Comment by paluchas** [comment]
Subsumed by other issues.
