### ISSUE TITLE
Link the journal title to journal homepage

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#172]
In the summary details view the the journal title in the publication reference should link to the journal homepage. As discussed in #145

**Comment by yf508** [comment]
@IAlferink Please update the journal list including the journal name and the urls.

From @em502:

"For now we have a finite set of about 12 journals. It won't grow to more
than about 20 max 30." from #145 

But we have about 60 journls in the current list: https://github.com/digital-york/oasis/blob/master/config/authorities/journals.yml

**Comment by IAlferink** [comment]
@Em502 I'm not sure about this. Can you please clarify?

**Comment by IAlferink** [comment]
@yf508 Sorry about the misunderstanding. We need all the journals that are currently on the list. In what format do you want the journals  + urls?

**Comment by IAlferink** [comment]
@yf508 Question: What happens to the journals in the 'other' category? Can we go in and link those manually? There won't be many as we have pretty good coverage of the field with the current list.

**Comment by yf508** [comment]
@IAlferink 

terms:
  - id: "URL_1"
    term: "JOURNAL 1"
  - id: "URL_2"
    term: "JOURNAL 2"

**Comment by IAlferink** [comment]
@yf508 Here's the list of URLs + journals.

https://docs.google.com/document/d/1X6F-nbj8_VQyWYW-T-wbXOwpmcqvXjUENNDLKFba3D0/edit?usp=sharing

**Comment by IAlferink** [comment]
@yf508 Thanks for fixing the other journal problem!
