### ISSUE TITLE
The reference in the 'how to cite this summary' box is not complete

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#176]
The reference for the summary when you click 'how to cite this summary' is not complete. It is missing the _OASIS_ _Summary_ of Surname, Surname, & Surname (year) in _Journal Title_. I also wonder about the square brackets and quotation marks around the names? I don't think they should be there as now it doesn't look the same as what we put on the actual summaries.

<img width="818" alt="screen shot 2018-08-03 at 10 01 53" src="https://user-images.githubusercontent.com/40735172/43634676-b14df3a0-9704-11e8-9214-26b7718bf381.png">

The complete reference should look like this:
<img width="619" alt="screen shot 2018-08-03 at 10 10 06" src="https://user-images.githubusercontent.com/40735172/43634926-74ac1246-9705-11e8-8cf5-2c1fe3a4d148.png">

**Comment by yf508** [comment]
I realize the problem with incorrect square brackets and quotation - it's a new problem introduced by the code implementing authors' order.

**Comment by yf508** [comment]
I've fixed the bug with square brackets and quotations. But as far as I remember, we've agreed that just use 'OASIS Summary' in the journal title field. So it looks like:

![image](https://user-images.githubusercontent.com/437701/43891014-34f78526-9bc0-11e8-9593-1d0b64de9e3a.png)

@IAlferink @RKasprowicz Please confirm with me if we need to construct the references as mentioned above?
![image](https://user-images.githubusercontent.com/437701/43891077-6091476c-9bc0-11e8-8475-95cb651efdb8.png)

**Comment by IAlferink** [comment]
@em502 I think we need your input on this one. I think it makes sense to have the 'how to cite this summary' the same on the website and pdf versions, but I don't know what has been agreed previously.

**Comment by RKasprowicz** [comment]
@yf508 @IAlferink @em502 I think the 'how to cite this summary' reference needs to appear with the journal name, as in the second example you give:

![image](https://user-images.githubusercontent.com/36402489/43891480-4df39050-9bc1-11e8-9aad-c48849a74657.png)

This is how we will want people to cite the summary (i.e. if they write something and reference the summary). I think it is important that this is consistent between the website and the reference as we have given it on the actual summaries, as you say @IAlferink. 

I can see that "in press" may be a problem in the future though.
I think we discussed 'in press' at the last meeting and agreed that summaries with 'in press' publications would be reviewed periodically and the date updated? (@em502 I think I am remembering correctly?)
If the date is updated (i.e. changed from 'in press' to 2019) in the main publication field, would this automatically update the date of the main publication in the 'how to cite this summary' field? @yf508 is this possible?

Alternatively, perhaps we could ask people to put the date for the main publication as the projected publication date, rather than "in press" to avoid this issue altogether? (i.e. if I have had an article accepted today that will appear in the journal next year, then I would put 2019, rather than in press?). But perhaps this could cause confusion.

**Comment by yf508** [comment]
@RKasprowicz Yes, it is how OASIS works now. As long as the data is updated in the form, it will be updated automatically in every page.

**Comment by em502** [comment]
ps -
yes, if people DO write 'in press', then we will have to periodically
update the online information manually, as we do with IRIS.

So... we will update the OASIS fields.

It will be a bigger job to take down the PDF, fish out our word version
that we have, change the date, PDF it, and re-upload. We will do this is we
have the capacity within OASIS staffing.
But... we might have to live with the 'in press' on the actual summary, and
the 'correct YEAR' in the online information stored on the OASIS database.
I think this is ok - as people should check out the most recent information
if they are writing 'in press' - e.g. editors and publishers make us check
this and update it.

e

**Comment by IAlferink** [comment]
@yf508 There are two things that still need resolving.

1) The initial should not be included in the last part of the reference (see arrow on picture). Everywhere else it is included, just not here.
<img width="778" alt="screen shot 2018-08-09 at 16 36 01" src="https://user-images.githubusercontent.com/40735172/43910147-ee807a9c-9bf3-11e8-8c34-de74cd1b7b9b.png"> 

2) Also in the last part of the reference, when there are more than 3 authors the reference should be author_1 et al. (year). So in the example below, it would be Doe et al. (2015). Again, this is only in this spot; everywhere else all names are listed.
<img width="760" alt="screen shot 2018-08-09 at 16 43 34" src="https://user-images.githubusercontent.com/40735172/43910259-3c1d71f6-9bf4-11e8-8f70-0c9bb948bb21.png">

**Comment by em502** [comment]
Inge and Frank may have this covered, but just in case:

if there are exactly three authors, the last bit would read
...of Doe, J., Noname, J., & Anonymous, J. (2015)...

if two:
..of Doe, J., & Noname, J. (2015)...

e


[image: screen shot 2018-08-09 at 16 43 34]

**Comment by IAlferink** [comment]
@em502 Yes, see above. But **without** the initials though.

**Comment by em502** [comment]
crumbs - yes - NO initials! sorry.

**Comment by IAlferink** [comment]
@yf508 There's a typo. It should be et **al.** not et **at.**
<img width="834" alt="screen shot 2018-08-16 at 11 41 04" src="https://user-images.githubusercontent.com/40735172/44204868-4e6aab00-a14c-11e8-8c19-b87f2eace5f0.png">

Also the last part of the reference is still not quite right. I'm sorry if I've been unclear about this.
1 author = fine
2 authors = fine
3 authors:
AuthorOne, AuthorTwo, & AuthorThree (2018)

More than 3 authors:
AuthorOne et al. (2008)

**Comment by IAlferink** [comment]
The last part of the **how to cite this summary reference** is still not quite right. My apologies if I've been unclear about this.
1 author = fine
2 authors = fine
3 authors:
AuthorOne, AuthorTwo, & AuthorThree (2018)

More than 3 authors (please note, no comma):
AuthorOne et al. (2008)

**Comment by IAlferink** [comment]
It's still not working correctly.

1)
**Exactly** 3 authors: AuthorOne, AuthorTwo, & AuthorThree (2018)

**More than** 3 authors: AuthorOne et al. (2008)

2) We want the initials included at the blue arrows, but not at the red one.
<img width="818" alt="screen shot 2018-08-20 at 09 53 56" src="https://user-images.githubusercontent.com/40735172/44330598-4f0e8480-a45f-11e8-817e-d4cbbb5c5875.png">

**Comment by yf508** [comment]
@IAlferink sorry for the bugs. Just updated the code and hopefully get it right this time.

**Comment by IAlferink** [comment]
@yf508 Looks good now. I have one last thing. Could there be a period after the initials please?

**Comment by yf508** [comment]
@IAlferink done.

**Comment by IAlferink** [comment]
@yf508 Great! Thanks
