### ISSUE TITLE
License information on upload form should be updated to reflect changes

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#183]
We are now only using one license. The language for the deposit agreement has been updated (see #153) and the other license option has been removed from the upload form. The language on the form should be amended to reflect that. 

1) Please, remove the entire _License_ section

2) Under the _License agreement_ header please add a short statement about the license type.

@yf508 I will provide updated language and link for the license agreement section

**Comment by IAlferink** [comment]
@em502 Now that we only have one license option do we need both these sections? Could we just remove the _license_ section altogether and add a short statement about the license type and a link to the cc website under the _deposit agreement_ header? Something along the lines of 'All OASIS summaries are published under an CC BY-NC-SA license. This means [xxx]. For more information see [link].
<img width="749" alt="screen shot 2018-08-10 at 16 34 19" src="https://user-images.githubusercontent.com/40735172/43967021-5192df54-9cbb-11e8-95d6-a0d450f56af0.png">

**Comment by em502** [comment]
Yes, just one set of information, no option, as you suggest. Yes i think we
can skip the license section. In fact... i think that Frank, Sebastian,
Rowena and I discussed this before and agreed just one license and no
selection therefore needed.

Thanks
Emma

**Comment by IAlferink** [comment]
@em502 Ah, I didn't know this had already been decided. I'll change the request.

**Comment by IAlferink** [comment]
@yf508 @em502 Here's the language: https://docs.google.com/document/d/1Rt1Xk4dmeDxJirrQcigxMXX_eRvPqtJXrWJ10qmGsNc/edit?usp=sharing
