### ISSUE TITLE
Remove 'private' from visibility options

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#187]
As discussed in #153, remove the 'private' option in the _visibility_ section. Please, also change the language under the 'Public' option to: 
Make available to all, pending check by OASIS team

<img width="366" alt="screen shot 2018-08-10 at 16 12 05" src="https://user-images.githubusercontent.com/40735172/43965814-2c84c8f6-9cb8-11e8-92a4-4011b8ff4ac6.png">

**Comment by yf508** [comment]
It's done in #153
