### ISSUE TITLE
Add text to the message depositors receive when we request changes

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#204]
To clarify the procedure when depositors have to make changes, please add the following text tp the message they receive:

Once you are ready to upload your amended summary, please follow these steps:

1) Go to the **summary details page** for your summary (you can get there by clicking on the ID in the message on your dashboard) and click on **Edit**
2) Upload your amended summary
3) Make any changes to the metadata fields (if necessary)
4) Press submit
5) **** **IMPORTANT** **** After you have submitted your amended summary, you need to return to the summary details page and 1) Click on **Review and Approval**, 2) tick **Request Review**, and 3) press **Submit**. This will let the OASIS administrator know that your summary is ready for them to check again before it is made live on the database.

**Comment by paluchas** [comment]
@paluchas This is a part of OASIS going live with all international researchers.

**Comment by paluchas** [comment]
# Fix Also Broken Link 
Requires also changes to broken link. See an example notification email as circulated to depositor when a change to record is requested. 
 
<img width="760" alt="requesting changes message" src="https://user-images.githubusercontent.com/1863245/48950658-d1fa1c00-ef33-11e8-8d22-c316724f95eb.png">

# Where
This will require to [overwrite config/locales/hyrax.en.yml](https://github.com/samvera/hyrax/search?q=requires+additional+changes+before+approval&unscoped_q=requires+additional+changes+before+approval). 

In addition this is an excellent opportunity to apply dedicated rspec test

**Comment by paluchas** [comment]
@IAlferink We have improved email notification. Can you test this on test.oasis-database system, please?

**Comment by IAlferink** [comment]
@paluchas I have tested this on the test system. The link in the email now works, that's great! 

However, when there is a comment-only I receive no dashboard or email notification. Also, no additional text (see first comment) has been added to the notification received when changes are requested:
<img width="751" alt="screen shot 2018-12-06 at 16 40 58" src="https://user-images.githubusercontent.com/40735172/49598100-d7b12200-f975-11e8-92ae-75304bd7320e.png">

**Comment by IAlferink** [comment]
@paluchas I still don't get the additional requested text (see description above) when I request changes from a depositor:

<img width="883" alt="screenshot 2019-01-30 at 11 51 04" src="https://user-images.githubusercontent.com/40735172/51979612-7beeab00-2485-11e9-9437-a3b707449014.png">

**Comment by IAlferink** [comment]
@paluchas Also, no email or dashboard notification when there's _comment only_.

**Comment by paluchas** [comment]
I have reinvestigated default Hyrax workflow behaviour, [see details in this evernote](https://www.evernote.com/l/AWd6Glbo72dCKrj2CmLpCJCe_8_UUMnRQ8s).

I have found out that, comments might confuse users expectation:
- Comments are not shown on neither admin or depositor notification boards
- Comments are not send as email to both admin and depositor
- Both admin and depositor will always get the same email wording that might be confusing
- Both admin and depositor will always get the same notification message that might be confusing
