### ISSUE TITLE
Change the order of the limit your search options

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#217]
We would like to change the order of the _limit your search_ options on the search results page if it's not too much work.

We would like the following order:
1. Topic
2. Language being learned
3. Participant type
4. Age of learner
5. First language of learner
6. Proficiency of learner
7. Language feature
8. Of likely interest to
9. Country
10. Context of language use
11. Gender of learners
12. Author of publication
13. Journal of publication
14. Date of publication
15. Materials on IRIS
16. Language summary written in

**Comment by yf508** [comment]
@IAlferink I don't see Author of publication, are you intending to remove it from this list?

**Comment by IAlferink** [comment]
@yf508 Sorry, mistake on my part. I've updated the list above.
