### ISSUE TITLE
Add "Of likely interest to..." metadata and search feature

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#24]
# Why
To provide information for the system users about the likely audiences for the summaries.

# Depositor/Uploader story
As a summary depositor during the upload step, I should be able to tick boxes to indicate the likely audiences for my summary. I can navigate to the field called **_Of likely interest to..._**. I can choose from a fixed drop-down menu one or multiple values from the following list
- Language learners; 
- Parents; 
- Policy-makers; 
- Professional development providers/Teacher educators; 
- Teachers [when we get hierarchies: pre-school; school 5-18 years; university]; 
- Test developers;
- University researchers;
- University students;
- Other [free text]

# User discovery story
As a website user, I should be able to narrow down my search results of summaries that are of likely interest to' ...’ through selecting facets (left side menu) and links (detailed view of the summary).

**Comment by yf508** [comment]
done.
