### ISSUE TITLE
Alignment of search results

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#242]
In the search results the alignment is different for each summary (see arrows below). Could they be made to look the same or is there a reason for this?
<img width="1330" alt="screen shot 2018-10-05 at 09 30 03" src="https://user-images.githubusercontent.com/40735172/46524719-a20e9080-c881-11e8-9d52-a60aabcb0127.png">

**Comment by websnacks** [comment]
Fixed the alignment, we need to test this on live system which has more records to show. Closing now, open again when alignment is incorrect after sprint update.
