### ISSUE TITLE
How to cite section is inconsistent

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#245]
I uploaded 2 summaries (both using chrome) and the _how to cite__ section appears different. In the first one the initials have disappeared for the summary authors. There is also a stray comma at the end after the journal name. I did enter them correctly in the metadata field.
<img width="836" alt="screen shot 2018-10-09 at 20 58 51" src="https://user-images.githubusercontent.com/40735172/46695307-21e08600-cc07-11e8-8faf-d89bd6edb91e.png">
https://oasis-database.org/concern/summaries/zg64tk92g?locale=en

<img width="821" alt="screen shot 2018-10-09 at 20 59 14" src="https://user-images.githubusercontent.com/40735172/46695319-2dcc4800-cc07-11e8-9552-9729b7bb4e6d.png">
https://oasis-database.org/concern/summaries/p2676v52c?locale=en

**Comment by IAlferink** [comment]
@yf508 I think this has something to do with selecting the 'Other' option for the journal as all the summaries where this happens are in journals that are not on our standard list.

**Comment by paluchas** [comment]
@IAlferink, please keep add some more examples for this issues.

**Comment by IAlferink** [comment]
@paluchas @yf508 The initials are now fine. However, now when I click on _other_ for _journal of publication_ no free text box appears. True both for Chrome 71.0.3578.98 and Safari 12.0 (14606.1.36.1.9)
<img width="749" alt="screenshot 2019-01-16 at 16 09 23" src="https://user-images.githubusercontent.com/40735172/51261997-505dc200-19a9-11e9-9aef-c6ec1e9c3e29.png">

**Comment by IAlferink** [comment]
@yf508 Sorry, I was on https://test.oasis-database.org. Should I be using the dev one now?

**Comment by yf508** [comment]
@IAlferink Yes, please test on dev.

**Comment by IAlferink** [comment]
@yf508 I now only have this issue on live website. Could it be something on my computer that's causing this?
