### ISSUE TITLE
Make summary attributes easier accessable

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#246]
In the current model, attributes are not registered in Solr document, therefore it's a bit complex to retrieve them from the view pages, e.g. @presenter.solr_document._source[field_name+"_tesim"]

We need a cleaner way to access these attributes

**Comment by yf508** [comment]
@IAlferink This issue involves lots of underlying code refactoring, when you review it, please use Oasis dev server as normal to see if everything is ok.

**Comment by IAlferink** [comment]
@yf508 I don't really understand what this issue is. Can you explain what it's supposed to do?

**Comment by yf508** [comment]
@IAlferink no new feature introduced in this issue. It's a process to refine the underlying source code, so when we implement new features in next sprint, it will be much easier.  Since there are lots of code changes, it would be great if you can help to test if I break anything.

**Comment by IAlferink** [comment]
@yf508 Ah, ok. Understood. Thanks for explaining. I'll have a look later today.

**Comment by IAlferink** [comment]
@yf508 The only thing I can find is that the journal title doesn't come through in the **summary details** and the **how to cite** sections.
<img width="1198" alt="screen shot 2018-10-14 at 15 57 21" src="https://user-images.githubusercontent.com/40735172/46918483-a5fd8980-cfca-11e8-8a8a-879ccdb3d0df.png">

**Comment by yf508** [comment]
@IAlferink thanks, it should be fixed.
