### ISSUE TITLE
Set PDF as file to download

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#257]
For every summary we upload a PDF and a word document. We need a copy of the word document in case we need to make any changes later. However, when someone downloads a summary we would like it to be the PDF. I think this used to be the case, but something has changed. For the following summary, for example, the download is is the word doc:
https://oasis-database.org/concern/summaries/ws859f652?locale=en 

I've tried changing this in the file manager, but that doesn't seem to do anything.

**Comment by paluchas** [comment]
@yf508 we need to assure that pdf file is always default download choice.

**Comment by IAlferink** [comment]
@yf508 @paluchas This issue is the problem Emma is referring to in her email today.
