### ISSUE TITLE
Change to a higher log level for production

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#258]
[This line ](https://github.com/digital-york/oasis/blob/f4f14a672ea74c9d41652bcc2a8cc6f55bea9538/config/environments/production.rb#L52)doesn't look right because it has caused a huge log file on live server:

```
config.log_level = Figaro.env.log_level == 'debug' ? :debug : :info
```
Needs to check dev/staging env as well.

**Comment by paluchas** [comment]
@yf508 I have tested this behaviour in my dev rails console and it works to me as expected. See

```
irb(main):018:0> fig_log_level = "debug"
=> "debug"
irb(main):019:0> log_level = fig_log_level == 'debug' ? :debug : :info
=> :debug
irb(main):020:0> fig_log_level = "info"
=> "info"
irb(main):021:0> log_level = fig_log_level == 'debug' ? :debug : :info
=> :info
irb(main):022:0> fig_log_level = nil
=> nil
irb(main):023:0> log_level = fig_log_level == 'debug' ? :debug : :info
=> :info
```

Maybe we changed log level in ```application.yml``` file manually. I'll test this on staging env too.

**Comment by yf508** [comment]
Should it be something like

log_level = fig_log_level? fig_log_level : :info

The old one makes the log_level either be 'debug' or 'info' ONLY.
