### ISSUE TITLE
IRIS_URL field doesn't appear at demo site

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#27]
Related to #25 

I can see that the IRIS icon and link show in brief search results.

I have noticed that in the demo site we have a bug. The hidden iris_url field doesn't show on Chrom and Safari as I tested this.

![screen shot 2018-02-15 at 13 53 14](https://user-images.githubusercontent.com/1863245/36262112-6bcba79e-125e-11e8-90a7-9a4181d4d75d.png)

We need to double check if this behaviour is different from the local vagrant dev.

**Comment by yf508** [comment]
fixed.
