### ISSUE TITLE
Change 'Topic' to 'Area of Research'

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#270]
@yf508 @paluchas Is it possible to change the facet name from _Topic_ to _Area of research_ on OASIS? We would like to make it more consistent with the language on the Resource Portal.

**Comment by IAlferink** [comment]
@paluchas As this was indicated to be quite easy, please do this.

**Comment by websnacks** [comment]
This means also changing the word **Topic** in the search results and on the resource page itself.
