### ISSUE TITLE
Links to browse by facet unavailable

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#273]
When I click on _all summaries_ or _topic_ or other facets n the homepage I get the error message below. This happens both in Chrome (71.0.3578.98) and Safari (Version 12.0 (14606.1.36.1.9)). Screenshot from Chrome.
<img width="928" alt="screenshot 2019-02-10 at 16 56 09" src="https://user-images.githubusercontent.com/40735172/52536615-c6f5a180-2d54-11e9-84fc-c215f25bd274.png">

<img width="1232" alt="screenshot 2019-02-10 at 16 55 51" src="https://user-images.githubusercontent.com/40735172/52536610-bb09df80-2d54-11e9-8b21-47d389722f1b.png">

**Comment by paluchas** [comment]
@IAlferink I'm investigating this and #271 right now. The later issues is more elusive. If I will not find a fix till tomorrow for #271 I'll push solution for this one (#273) to production asap.
