### ISSUE TITLE
Initial disappears from How to cite section

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#281]
On the summary details page one of the author's initials (the middle name initial) disappears in the publication field:

<img width="822" alt="screenshot 2019-02-22 at 12 31 20" src="https://user-images.githubusercontent.com/40735172/53244265-41ea8080-36a2-11e9-8932-0577b8137798.png">

I have entered the initial correctly in the upload form:

<img width="253" alt="screenshot 2019-02-22 at 12 31 43" src="https://user-images.githubusercontent.com/40735172/53244345-88d87600-36a2-11e9-905f-6784c9546d19.png">

The same thing happens with the middle initial for the summary writer in the how to cite section:

<img width="322" alt="screenshot 2019-02-22 at 12 31 27" src="https://user-images.githubusercontent.com/40735172/53244388-a4dc1780-36a2-11e9-9e6d-7689014bef8e.png">

Again, I have entered it correctly on the form:

<img width="301" alt="screenshot 2019-02-22 at 12 31 39" src="https://user-images.githubusercontent.com/40735172/53244410-b4f3f700-36a2-11e9-8564-39fdb365155b.png">

The same issue then occurred with another summary I uploaded. I used Chrome Version 72.0.3626.96

**Comment by IAlferink** [comment]
@paluchas I just had author emailing me about this, so I just wanted to check whether this issue is any closer to being resolved?

**Comment by paluchas** [comment]
@IAlferink I have applied change in the code that resolves this bug. I have checked [the record ](https://oasis-database.org/concern/summaries/6d56zw644?locale=en) reported and al linitial shows the page.
