### ISSUE TITLE
Change to homepage text

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#290]
@paluchas On the OASIS homepage, could you change the text under _Want monthly alerts of new summaries?_ to:

[Sign up](https://mailchi.mp/481ba176f2d1/oasis-alerts) for our newsletter!

**Comment by paluchas** [comment]
@IAlferink , see https://test.oasis-database.org/?locale=en. Once #291 is ready we can add both to the live system.

**Comment by IAlferink** [comment]
@paluchas This looks fine, once the tabs have been reorder this can go live.Thanks
