### ISSUE TITLE
Add tab to homepage

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#291]
Can we please add a new tab called _Supporting journals_ to the homepage?

**Comment by paluchas** [comment]
@IAlferink See this link https://test.oasis-database.org/supporting_journals - If you are happy we can add this change to production. 

BTW. I can also reorganise order off the links in the menu. Just let me know the correct one.

**Comment by IAlferink** [comment]
@paluchas yes, please reorder the tabs. Can I have:
- Home
- Upload summary
- About
- Supporting journals
- Help
- Activities
- Feedback
- Contact

Looks fine in Chrome, but the tab moves to another line in safari (for me - Version 12.0 (14606.1.36.1.9)).
<img width="1338" alt="Screenshot 2019-06-21 at 17 09 50" src="https://user-images.githubusercontent.com/40735172/59936436-e958a380-9447-11e9-9f57-75141a6cbd48.png">

**Comment by IAlferink** [comment]
@paluchas Could you please have another look at this?

**Comment by paluchas** [comment]
@IAlferink I have applied changes to live site. This include reordered menu pages. I have left empty space in new tab so you can move the content from the about page yourself. 

I was not able to replicate issue with Safari. From a screenshot, I can see that you were logged. Could it be that you were not logged in on Chorome? The difference will be additional tab "upload summary" appearing. This could explain the differences between two browser you saw.

**Comment by IAlferink** [comment]
@paluchas Thanks for sorting this. I will move the content. You are right, when I'm logged out it's not an issue, so it's the extra _upload summary_ tab that's the problem.
