### ISSUE TITLE
Enable cards for Twitter

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#294]
Make previews available for tweets of OASIS summaries.

For example:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

**Comment by yf508** [comment]
Ref: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image

**Comment by paluchas** [comment]
#349 resolves some issues.

**Comment by IAlferink** [comment]
@paluchas Thanks for your work on this. It's exactly what I meant and I like it. I was wondering if we could tweak two things? I don't know how much freedom Twitter gives you, but ideally I would like the following:
1. Thumbnail instead of logo.
2. Complete summary title visible.
<img width="636" alt="Screenshot 2021-02-26 at 10 02 36" src="https://user-images.githubusercontent.com/40735172/109287587-aef9f900-781b-11eb-92d4-755975d667c2.png">

**Comment by paluchas** [comment]
Re 1 - I'm intending to correct this functionality so thumbnails show as default and the OASIS logo for backup when thumbnails are missing. 
Re 2- We are presenting whol tilltel. I suspect Twitter has some character limit. Will check their documentation to clarify this behaviour.

**Comment by paluchas** [comment]
Metadata for the Twitter card are presenting a link to the thumbnail image.
