### ISSUE TITLE
Make summary details page more user friendly

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#298]
We were a little surprised by the difference between the number of users and the number of downloads on the OASIS website. We'd like to make some changes to the _Summary Details_ page.

Can we (in order of priority):
1. Move the thumbnail to the top above the summary details and make it big enough for people to read on the page.
2. Make the download pdf button more prominent.
3. Collapse the _Summary details_ (like the _more participant details_ and _how to cite_ sections)
4. Remove the _public_ and _deposited_ labels from the public view.

<img width="1434" alt="Screenshot 2019-10-09 at 12 19 33" src="https://user-images.githubusercontent.com/40735172/66477343-cc47ef00-ea8f-11e9-81e7-481637f886cc.png">

**Comment by websnacks** [comment]
I have made an update to the details page. Please take a look once it's on staging. We can make further improvements based on this.

Download button is full width should be same size as preview image.

Note: the admin buttons are now on the bottom of the page so title can be full width.
Note: social media buttons are under the Summary details.
