### ISSUE TITLE
Homepage: Content for tabs (About, Help, Contact us)

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#30]
OASIS team would like to have admin access to create content text for About, Help, Contact us pages (in the first stage). 

Images, videos, screenshots will be added by dev team in later stage.

![image](https://user-images.githubusercontent.com/36402489/36531356-75b30d72-17b5-11e8-9f0a-93912664eeab.png)

**Comment by em502** [comment]
i hope this can be squeezed in!
