### ISSUE TITLE
Summary detailed view page - authors' names in publication reference

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#32]
Currently the full reference (next to "**publication**") is not being generated in APA format.

Do we want all authors' names to appear or just the first author with et al.?

e.g. 1) Andringa, S., de Glopper, K., & Hacquebord, H.
       2) Andringa, S., et al. 

The former may be more complex. 

Sophie will provide some examples of APA format generated by other reference tools such as Endnote 

![image](https://user-images.githubusercontent.com/36706240/36537482-2902effc-17c8-11e8-898e-9f0d91a5f6db.png)

**Comment by RKasprowicz** [comment]
@paluchas @SophieThompson In the meeting this morning, we discussed several options to resolve this. 
I have checked with Emma and the preference from the available short term solutions would be to duplicate the "author of publication" field (and the "writer of summary field") - in one, Sophie can then enter all authors in one single entry, which will be used to populate the "Publication" field on the Search results and Detailed summary view pages. In the second, Sophie can then separately list all authors, and these entries will be populate the search list.

@paluchas Please can you confirm that this is possible?

**Comment by RKasprowicz** [comment]
Note this issue links to issue #29

**Comment by paluchas** [comment]
@yf508 Pleas, see last comments here. The proposal is to modify the metadata model to include an additional publication author field to provide a correct order of authors for the citation purpose. We should discuss this in the following Monday 12th March.

**Comment by yf508** [comment]
Assuming the entered authors will be APA formatted?

**Comment by RKasprowicz** [comment]
Yes the reference should be APA formatted please.

When Sophie and I were doing testing yesterday, the authors seemed to be appearing in the correct order. However, today they are not (for all entries with multiple authors).  If the only way for the authors to appear correctly is by having an additional field for authors where names are entered in a single row to populate the APA reference, then yes please do this.

**Comment by yf508** [comment]
@RKasprowicz what I meant was that if you/Sophie enter multiple authors in a single textbox, you will follow APA while entering and the application doesn't need to do any formating for authors?

**Comment by RKasprowicz** [comment]
@yf508 Yes, If we are entering multiple authors in a single textbox we will follow APA format. 
But, please note - having an additional box where we enter multiple authors (as well as entering authors separately), is the work around we agreed to for now (for the March deadline), as it is not possible to sort out the ordering problem in the short term. Is this still the case?

**Comment by yf508** [comment]
This should be fixed together with #29

**Comment by RKasprowicz** [comment]
@paluchas I have changed label to UAT - ready as the temporary fix (All authors of publication field) is working.

**Comment by SophieThompson** [comment]
@RKasprowicz Can I just check, I should enter the authors using APA i.e. with & (see below)

![image](https://user-images.githubusercontent.com/36706240/37357503-85ae4c66-26e0-11e8-8f2f-c08bf89a46c2.png)

If so, then it's not including the ampersand... 

![image](https://user-images.githubusercontent.com/36706240/37357537-9ce49412-26e0-11e8-87d0-3690ed67a4b8.png)

**Comment by RKasprowicz** [comment]
@SophieThompson Yes, we need to enter as APA, so with the & (for the "All writers of summary" field, as with the "Publication authors all" field. I've created a separate issue #98 as the "Writer of summary" field, and "How to cite this summary" field are not currently pulling the information from the "All writers of summary field", and so leaving out the &.
