### ISSUE TITLE
Summary results page: Search facets missing

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#33]
Currently some of the fields are missing from the facets in the search, as specified in the Revised_SearchResults page document sent on 21/02/2018.
[Revised_SearchResultsPage RK_EM Feb 2018.pptx](https://github.com/digital-york/oasis/files/1750697/Revised_SearchResultsPage.RK_EM.Feb.2018.pptx)

Please see screenshots below (left for current and right for desired):

This may be because there are no records on OASIS with information completed for the missing facets i.e. age of learner is not captured in any record. 

To test this Sophie will create a record with all the fields completed to see if then all the search facets appear. 

![image](https://user-images.githubusercontent.com/36706240/36537961-a805276a-17c9-11e8-8365-a1409655a551.png)

**Comment by paluchas** [comment]
@SophieThompson There are still some facets missing in our configuration file, the current list is encoded in source code [here](https://github.com/digital-york/oasis/blob/8f4e8ee909049109d950c483f22e15480dcd1cd9/app/controllers/catalog_controller.rb#L50-L62)

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson what do you expect to see in "Materials on IRIS" as a content. Those would be only URLs as far as I understand?

**Comment by RKasprowicz** [comment]
@paluchas There would be two options Yes / No (or perhaps just one option --> Yes). So that the user can filter results by only searching for summaries that also include a URL link to resources on IRIS.

**Comment by SophieThompson** [comment]
@paluchas I've made a record with all the fields filled in and still there are missing facets on the search, so it doesn't relate to lack of records containing facets. 
As an aside the summary record page looks good and all the fields show. I've put NA in some fields for now so that I could complete them (I'll remove these in the future) @RKasprowicz FYI
