### ISSUE TITLE
Add Journal to the options in drop to menu

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#332]
A new journal has joined OASIS. Could you please add it to the drop down list in the Journal of Publication drop down list?
<img width="796" alt="Screenshot 2020-08-13 at 12 07 34" src="https://user-images.githubusercontent.com/40735172/90127743-95043780-dd5d-11ea-9b25-ca628a116b06.png">

Name of journal: **Journal of Language, Identity & Education**
Homepage: https://www.tandfonline.com/loi/hlie20

**Comment by yf508** [comment]
Done.
