### ISSUE TITLE
Search results page - metadata field to be displayed

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#35]
The current record summary facets displayed need to be updated, as specified in the Revised_SearchResults page document sent on 21/02/2018. 
[Revised_SearchResultsPage RK_EM Feb 2018.pptx](https://github.com/digital-york/oasis/files/1750655/Revised_SearchResultsPage.RK_EM.Feb.2018.pptx)

Please see screenshots below of the current design (top), vs. our desired design (underneath):

![image](https://user-images.githubusercontent.com/36706240/36538371-17fa0f62-17cb-11e8-88a7-3e8ff7d82d61.png)

**Comment by em502** [comment]
please use the slides that i sent (for example, we asked for Language to be one of the summary facets displayed)

**Comment by RKasprowicz** [comment]
@em502 Language being learned is currently included on the Summary detailed view (slide 2 in the ppt document). But it is not included in the search results page (slide 1 in the ppt document, and screenshots above). Is this ok?
