### ISSUE TITLE
Search results page - labels showing as numbers not text

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#36]
The following fields currently show a numerical value corresponding to the position of the label in the list rather than the text label

Topic, Language being learned, journal etc. All text fields were showing as numbers. 

![image](https://user-images.githubusercontent.com/36706240/36538521-c06acd80-17cb-11e8-8d49-472b60dc73c0.png)

**Comment by SophieThompson** [comment]
@yf508 This now seems to be resolved? Is that correct? 
@paluchas should Rowena or I now test this? We could assign a new label - ready to test?

**Comment by SophieThompson** [comment]
Actually having logged in I can see this is still an issue:

![image](https://user-images.githubusercontent.com/36706240/36539210-ee25b36e-17cd-11e8-8c18-f066db6fefc2.png)

**Comment by yf508** [comment]
@SophieThompson No, it's not fixed. I know how to fix it in detail page but not the search result page yet.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson demo site contains now #59 pull request for testing. If it works, please indicate this with  "UAT - ready" label at #59
