### ISSUE TITLE
Uploading leads to error page

### ISSUE THREAD

**Issue by IAlferink** [digital-york/oasis#368]
When uploading a summary in Chrome for PC  90.0.4430.212 I always see the following screen after pressing _submit_:
![Error message](https://user-images.githubusercontent.com/40735172/119355034-aab76d80-bc9c-11eb-9aed-eef913d251d7.png)
Reloading the page solves the issue and allows me to proceed. It's not a serious problem, but it's also not working as it should, so I'm logging it here.

**Comment by paluchas** [comment]
@IAlferink can you add information on what record have you been working, please?

**Comment by IAlferink** [comment]
@paluchas I see the error message for every summary I upload. The summary I was talking about in the email is [this one](https://oasis-database.org/concern/summaries/s7526c76q?locale=en).

**Comment by paluchas** [comment]
Some relevant error logs
```
oasis@dlibpubprod0:~/current/log$ cat production.log | grep "s7526c76q"
F, [2021-05-25T10:06:09.262536 #24354] FATAL -- : [16db9c75-585b-49ec-b990-3d12ae35ebe9] ActionController::RoutingError (No route matches [GET] "/concern/workflow_actions/s7526c76q"):
F, [2021-05-25T10:06:11.032236 #24354] FATAL -- : [6d293477-a92b-4066-b516-9bc2bea74e18] ActionController::RoutingError (No route matches [GET] "/concern/workflow_actions/s7526c76q"):
F, [2021-05-25T10:06:12.588806 #24723] FATAL -- : [1ba05e67-29b2-45c7-946a-694948642e1c] ActionController::RoutingError (No route matches [GET] "/concern/workflow_actions/s7526c76q"):
```

**Comment by paluchas** [comment]
I can see that files were uploaded on `25/05 9:05 - 9:47am`. I cannot see any errors in Apache or Hyrax stack at this time. I was not able to reproduce the 500 error screen.
