### ISSUE TITLE
Homepage - search bar

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#40]
There should be a central search bar on the homepage as specified in he Revised_Homepage document sent on 21/02/2018. 
[Revised_HomePage_RK_EM 21 Feb.pptx](https://github.com/digital-york/oasis/files/1750677/Revised_HomePage_RK_EM.21.Feb.pptx)

Please see screenshots and a breakdown of features below:

![image](https://user-images.githubusercontent.com/36706240/36539264-1cd74c5e-17ce-11e8-8c1b-bf4614365184.png)

Clickable links below the bar to key search areas. When click on this will open a pop-up to allow a user to search within one field e.g. a pop-up like the ones on the search results page when "more" is clicked (see below)

![image](https://user-images.githubusercontent.com/36706240/36539260-1720dec4-17ce-11e8-8950-13fa6003a98e.png)

**Comment by SophieThompson** [comment]
Additionally for homepage:

Add "funded by" and remove list of collaborators etc (see below):

![image](https://user-images.githubusercontent.com/36706240/36544681-f4059ec8-17de-11e8-9c90-3a8486de638f.png)

Do the ESRC and BA logos need to be on every page?

**Comment by paluchas** [comment]
Should be resolved together with #54
