### ISSUE TITLE
"About" tab

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#41]
On the "About" tab insert info about the project team etc. Retain as dropdown lists (user clicks on heading to view list of people)

As on other pages add tabs across the top (upload summary etc.)

![image](https://user-images.githubusercontent.com/36706240/36544808-43d989fa-17df-11e8-8b10-bf8b007a707a.png)

**Comment by RKasprowicz** [comment]
There is currently no information displaying on the About page (see below). The original information (information about project team and about the OASIS project) that was on this page needs to be displayed. 

![image](https://user-images.githubusercontent.com/36402489/37159324-6fdf3322-22e5-11e8-834a-b141223fb3ac.png)

**Comment by paluchas** [comment]
Related to #66

**Comment by yf508** [comment]
If the about page is in content blocks, assuming like images, the clickable accordions won't be possible?
