### ISSUE TITLE
"Contact us" tab

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#42]
This page just needs simple text as shown below with oasis@oasis-database email address 
This relates to issue #31 once #31 is done then the email address can be changed to oasis@oasis-database 

As shown below remove language options and add tabs

![image](https://user-images.githubusercontent.com/36706240/36545067-ee3b8baa-17df-11e8-9972-5b03216a48bc.png)

**Comment by paluchas** [comment]
@SophieThompson I think we should leave the contact form as it is. We can review the reported issue type categories list and form wording to guide users for more detailed communication. 

We will configure the production system in such way that all forms will be circulated to iris admin account.

**Comment by paluchas** [comment]
@SophieThompson @RKasprowicz I have configured email delivery on production to oasis@oasis-database.org. I have sent a comment on the web form. Can you confirm if this has been delivered successfully to IRIS/OASIS account?

Let me know if we need to alter the current contact form wording.

**Comment by SophieThompson** [comment]
Hi, I replied by email, but for this record, yes it worked. Thanks!
