### ISSUE TITLE
Summary detailed view page: Finalised design

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#43]
The Summary detailed view page should be implemented as specified in the Revised_SearchResults page document sent on 21/02/2018. 
[Revised_SearchResultsPage RK_EM Feb 2018.pptx](https://github.com/digital-york/oasis/files/1750655/Revised_SearchResultsPage.RK_EM.Feb.2018.pptx)

Please see screenshots and a breakdown of features below.

![image](https://user-images.githubusercontent.com/36402489/36553918-8ecf1388-17f5-11e8-8b80-78eb402eb543.png)

The metadata fields will be grouped under three subheadings. 

First, "Summary details", which will be the default information displayed to the user and includes the following metadata fields: 

![image](https://user-images.githubusercontent.com/36402489/36554112-2517828a-17f6-11e8-8ad3-ae08d029b330.png)

The second subheading is "More participant details". The user can click on this subheading to display the following metadata fields:

![image](https://user-images.githubusercontent.com/36402489/36554088-0997e504-17f6-11e8-8c21-0b96903245a7.png)

The third subheading is "More study details". The user can click on this subheading to display the following metadata fields:

![image](https://user-images.githubusercontent.com/36402489/36554183-6300f3e2-17f6-11e8-9987-f73bc7c0a66a.png)

Beneatht the thumbnail image of the pdf, the user can click on the dropdown "How to cite this summary". The citations for the summary will be displayed and should be constructed as follows:

![image](https://user-images.githubusercontent.com/36402489/36554296-ca0348ec-17f6-11e8-9949-6ccf2c233882.png)

**Comment by RKasprowicz** [comment]
To test this I uploaded a new version of the Kasprowicz and Marsden summary. I entered information in all of the fields in the upload form; however some of the fields are missing from the summary detailed view form. 

The missing fields are:
For the Summary details section:
- Of likely interest to 
- IRIS Materials (the field is displaying but there is no URL as I was not able to enter one of the upload form)

For the More participant details section:
- Context of language use
- Years of teaching experience
- Amount of prior instruction

Please also correct the first subheading to "Summary details" (there is a spelling mistake)
![image](https://user-images.githubusercontent.com/36402489/36723112-3b73d876-1ba7-11e8-9506-70cf54f1dbb8.png)

**Comment by SophieThompson** [comment]
The summary detail section now has "of likely interest to" but is still missing IRIS URL

The More participant details section is still missing the three fields from the above issue (see image below)

![image](https://user-images.githubusercontent.com/36706240/37163229-21e512ae-22ef-11e8-9d7b-3b86392a79e7.png)

**Comment by SophieThompson** [comment]
I have deleted the old summaries and have uploaded a new one.
These fields (see above image) are still missing:

![image](https://user-images.githubusercontent.com/36706240/37297022-8a4f9f30-2614-11e8-8a79-194fa027346c.png)

**Comment by paluchas** [comment]
I have corrected the spelling mistake in the summary now.

**Comment by SophieThompson** [comment]
@paluchas great! thanks.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson Demo site should now show all More participants details information.

**Comment by RKasprowicz** [comment]
@paluchas All metadata fields now appear on the summary detailed view page (as long as information has been given for the field)
