### ISSUE TITLE
Upload form: Remove embargo / lease / OASIS categories from "Visibility" dropdown

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#47]
Remove the categories embargo / lease / OASIS from the "Visibility dropdown. Retain the public and private options

![image](https://user-images.githubusercontent.com/36402489/36555715-b7165798-17fa-11e8-82f1-1c1c248c22ad.png)

**Comment by paluchas** [comment]
It should be resolved with #63
