### ISSUE TITLE
Upload form: Change order of tabs / actions in upload process

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#48]
Change order of tabs so that user is asked to upload the pdf summary file first and then is asked to provide the metadata. The order should be: Files; Descriptions; Share. Remove the "Relationships" tab.

![image](https://user-images.githubusercontent.com/36402489/36555808-fba0f440-17fa-11e8-8e14-b68f6b019f16.png)

From the "Files" page, remove the option to "Upload folder". User will only ever upload one summary (one pdf file) at a time.

**Comment by SophieThompson** [comment]
This is done:

![image](https://user-images.githubusercontent.com/36706240/37162602-8d43c72c-22ed-11e8-95b1-92b4a8e6a857.png)
