### ISSUE TITLE
Upload form: Add "Hold down Ctrl to select more than one term" to multiple choice fields in upload form

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#49]
The instruction "Hold down Ctrl to select more than one term" needs to be added to the description for the following multiple choice metadata fields: Topic; Language feature; Participant type; First language of learners; Language being learned; Age of learners; Proficiency of learners; Context of language use; Of likely interest to. 

The following multiple choice fields do not need this instruction, as the user will only select one value: Year of publication; Journal of publication; Gender of learners; Materials on IRIS;

**Comment by yf508** [comment]
done.

**Comment by paluchas** [comment]
Sadly on MacOS, this is not Ctrl but Command key
