### ISSUE TITLE
Searching: Full list of available search terms for each metadata field needs to be provided for users to refer to.

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#50]
The full list of search terms available for each metadata field need to be displayed for the user to refer to when conducting searches.

**Comment by em502** [comment]
this is really important - the list (the ontologies) have to be there
we will be demonstrating a search and sending the link out so people might search.

**Comment by RKasprowicz** [comment]
@yf508 @paluchas Please can the lists of search terms be implemented as dropdown lists on the Help page, as below:

![image](https://user-images.githubusercontent.com/36402489/36580991-9672cce8-1862-11e8-97ab-6743cb6a5954.png)

Full list of search terms includes all terms specified in [Updated_OASIS Search Terms](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit?usp=sharing)

**Comment by paluchas** [comment]
This is related to #30 we will enable admin editing for this page before 1st March. You will be able to enter/edit the list with basic formatting. We can add drop down menu later once other high priorities will be resolved.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson We discovered a bug, see #66. Once resolved you should be able to edit those pages.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson The demo and production https://oasis-database.org allow now for editing the help page. Please, edit demo and we will copy it to production once ready.

**Comment by RKasprowicz** [comment]
@paluchas The help page on the demo site has now been updated with the full list of search terms.
