### ISSUE TITLE
Upload form: Remove duplicate "licence agreement field"

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#51]
The user is asked in two places to agree to the licence agreement. Please remove this field from the main set of metadata fields 

![image](https://user-images.githubusercontent.com/36402489/36556530-6fc83494-17fd-11e8-82ae-8a9206132287.png)

And retain the field under the Visibility tab:

![image](https://user-images.githubusercontent.com/36402489/36556555-822d1b18-17fd-11e8-97c4-1e36433ee2fa.png)

**Comment by paluchas** [comment]
Resolved with #70
