### ISSUE TITLE
Home page: All summaries option

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#54]
An important function for the search interface is for the user to be able to 'Find everything on OASIS' and then use the filters to refine the search. (This is similar to IRIS - on IRIS we are able to just pull up everything which is really useful for demonstrating it.)

Our suggestion for implementing this is to:
1. Insert an option for the user to browse "All summaries" (clicking this link would bring up all summaries in OASIS)
2. Insert a description below the search box, explaining that the user can view All Summaries and then use the filters to refine their search.
See image below:

![image 6](https://user-images.githubusercontent.com/36402489/36665508-abd1a896-1adf-11e8-97df-ea00da5dd5ec.png)

This is a high priority task - we will need the "All summaries" link to be in place and working in time for demoing the system in March.

**Comment by paluchas** [comment]
This is related to #40.

For information @RKasprowicz @SophieThompson. By default, the empty search brings all Hyrax content e.g. press "Go" without entering any text in the search box.

**Questions**: Do you still prefer "All summaries" link? Or we can replace an additional text _Click "All summaries" ..._ txt with _Click "Go" button ..._

**Comment by SophieThompson** [comment]
So a link saying "click Go" or just the "Go" button with some text saying "click "go" to see all summaries"? Just double checking if I've understood. What do you think Rowena? @RKasprowicz

**Comment by paluchas** [comment]
@SophieThompson Yes, that's correct.

**Comment by yf508** [comment]
the 'other' link needs more time to implement. I would leave it for now and spend time on other high priority issues.

**Comment by RKasprowicz** [comment]
@paluchas @SophieThompson @yf508 If clicking Go (when the search box is empty), brings up all of the OASIS content, then I think we can use that. 

So, yes - do not implement the All summaries link. Instead, can we change the bottom line of the description under the search box to:

"Leave the search bar empty and click "Go" to view all content on OASIS and then use the filters to refine your search results"

**Comment by RKasprowicz** [comment]
@yf508 I agree, the "Other" link (under the "Browse by:" options) is lower priority, so focus first on the other high priority issues.

**Comment by yf508** [comment]
@RKasprowicz "All summaries" link has been done - just remove 'other' link for now. So the current homepage looks like:

![image](https://user-images.githubusercontent.com/437701/36838865-40100e9e-1d38-11e8-9a02-f1b6e20fe022.png)

**Comment by paluchas** [comment]
@SophieThompson @RKasprowicz the home page has been updated on the demo site too. I had briefly tested it and it works as expected. 

A couple of things for the future improvements: 
- Change default behaviour when the browsable link is open. Currently, it will reload the whole page content. We should aim to replace this behaviour with a pop-up window.
- The free text search is misconfigured at demo site and will not bring search results as expected. The facet search work ok.

**Comment by RKasprowicz** [comment]
@yf508 The screenshot of the home page you have provided looks good, thank you Frank. And good that the All summaries link is in there - let's stick with this for now (please ignore my comment from yesterday).
I can't access the demo site to test the home page and links until Monday, but will test as soon as I can.

@paluchas Please could you explain a bit more about the free text search not bringing up search results correctly - I'll test this on Monday, but could you please explain what the issue is at the moment and what will / won't work. Thank you.

**Comment by yf508** [comment]
done.
