### ISSUE TITLE
Upload form: box to enter URL for materials on IRIS is no longer visibile

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#57]
There is no longer a box to enter the URL to materials on IRIS. There is only a Yes/No option

![image](https://user-images.githubusercontent.com/36402489/36722441-6a825dba-1ba5-11e8-933b-567804ec0fff.png)

**Comment by paluchas** [comment]
@RKasprowicz this but has been introduced once we moved an original order of Metadata tab behind the Files tab. One way of forcing URL box to appear is:
- press edit summary
- open Metadata tap
- select Yes/No option
- reload browser page
- Now the URL box should appear

This is a temporary work around before we will fix this in the code.

**Comment by RKasprowicz** [comment]
@paluchas thank you for the work around - this will work for now.

@SophieThompson fyi for when you're uploading more summaries
