### ISSUE TITLE
Data Dictionary management

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#6]
A data dictionary tool is needed to manage (hierarchical) terms, e.g. to perform basic CRUD operations and the underlying code to make sure the data is consistent, especially while updating/deleting DD.

Terms list can be viewed [here](https://docs.google.com/spreadsheets/d/1rGBsH857eKLQgozQR_pAzROjZtFl-e2Jd3jcwojekSo/edit#gid=1971710027).

**Comment by paluchas** [comment]
Not required at this sprint. We will require more discussion in the future with OASIS what functionality is required.
