### ISSUE TITLE
Visibility settings not working

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#63]
Even we set the visibility to 'public' in the OASIS form, it always stores as 'private'

![image](https://user-images.githubusercontent.com/437701/36980311-dbd79c56-2081-11e8-9b07-7149aa67baef.png)

**Comment by paluchas** [comment]
@yf508 I have compared OASIS versus Hyrax-Demo. Here are some of my findings of this issue.

When visibility status is changed the step is confirmed by calling additional route. The example path is here
```
/concern/permissions/xg94hp52v/copy_access
```

On a Fedora level, a record links to more Hydra::AccessControl objects. For example an record with publis status will have following permission in the Fedora
```
irb(main):009:0> b.permissions
=> #<Hydra::AccessControl::CollectionRelationship:0x00000007f23738 @owner=#<Hydra::AccessControl id: "f09a9b63-6454-46f9-ad2c-671427e60870">, @relationship=[<Hydra::AccessControls::Permission id: f09a9b63-6454-46f9-ad2c-671427e60870/04/5a/31/1b/045a311b-1eac-4b06-b971-195cd4714b6e agent: "http://projecthydra.org/ns/auth/group#registered" mode: "http://www.w3.org/ns/auth/acl#Read" access_to: "tt44pm84n">, <Hydra::AccessControls::Permission id: f09a9b63-6454-46f9-ad2c-671427e60870/a6/59/85/d0/a65985d0-bf4d-465c-b14e-ae480a818dff agent: "http://projecthydra.org/ns/auth/person#sebastian.palucha@york.ac.uk" mode: "http://www.w3.org/ns/auth/acl#Write" access_to: "tt44pm84n">, <Hydra::AccessControls::Permission id: f09a9b63-6454-46f9-ad2c-671427e60870/c1/89/a2/1b/c189a21b-f816-4f24-9904-b56ab7cc18ad agent: "http://projecthydra.org/ns/auth/group#admin" mode: "http://www.w3.org/ns/auth/acl#Write" access_to: "tt44pm84n">]>
```

Comparing this versus our OASIS record gives the follwoing permission
```
irb(main):004:0> s.permissions
=> #<Hydra::AccessControl::CollectionRelationship:0x0000000cb10c68 @owner=#<Hydra::AccessControl id: "6b38ab4e-4e42-457c-99b3-f6e40dfaadbc">, @relationship=[]>
```

Some other difference between Hyrax-Demo and our OASIS is that Hyrax-demo is not using _hydra-role-management_ gem.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson A new code has been added to demo to solve this.  I have tested this on my local dev and it worked for me.
