### ISSUE TITLE
TINYMCE doesn't work at demo site

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#66]
On my local dev, I can edit a content of some static pages. 
![screen shot 2018-03-06 at 09 55 37](https://user-images.githubusercontent.com/1863245/37025797-904bbc24-2124-11e8-828c-dd40ef0ded16.png)

On the demo, TINYMCE is not rendering correctly. 
![screen shot 2018-03-06 at 09 56 26](https://user-images.githubusercontent.com/1863245/37025871-bb851e44-2124-11e8-80a8-71cd34c43329.png)

Could it be a firewall issue?

**Comment by paluchas** [comment]
This could be related to turbolinks. Following advice is from [Hyrax Managment Guide - User Interface](https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide#user-interface)

If you encounter problems with the in-browser content editor -- e.g., the About page, and the three blocks on the homepage -- you should remove turbolinks support from ```app/assets/javascripts/application.js``` if present by deleting the following line:

```
//= require turbolinks
```

**Comment by yf508** [comment]
@paluchas I think turbolinks is enabled by default as it makes links faster. Let's see if the changes break anything or bring any side effects.

**Comment by paluchas** [comment]
It is resolved with this commit https://github.com/digital-york/oasis/commit/4174bfdf23bfd1373738f20cd7425a5415f3106b
