### ISSUE TITLE
Full text search not working

### ISSUE THREAD

**Issue by yf508** [digital-york/oasis#67]
User should be able to do full text search on all fields:
* For text fields, search the text being entered
* For fields linking to authorities (dropdown from data dictionaries), although ONLY the id of authority item stored in solr, the label of authorities should be searchable as well

**Comment by SophieThompson** [comment]
I've had a go at some more searches but I think the same problem still exists (see below)
A term which is in an existing record (implicit) does not produce results in the search

![image](https://user-images.githubusercontent.com/36706240/37161513-c84b6f58-22ea-11e8-8f4c-c9079e292b25.png)

**Comment by SophieThompson** [comment]
@paluchas @yf508 @RKasprowicz 
I will test this out with the newly uploaded summaries tomorrow morning

**Comment by SophieThompson** [comment]
@paluchas @yf508 @RKasprowicz

I have tested this now using terms from the 2 new summaries. It seems _author_ works and _date._ As you'll see below the term "English" worked, but I'm not sure if it's matching this to languages learned, first language or just a summary title (results for "English" shown below.)
The table below shows you the term I typed into the search bar, its corresponding facet and whether any result came back. 

![image](https://user-images.githubusercontent.com/36706240/37299418-2a1d3120-261b-11e8-8d50-072f327d40fa.png)

![image](https://user-images.githubusercontent.com/36706240/37299429-35c1150a-261b-11e8-9c53-ab022d3611a6.png)

**Comment by SophieThompson** [comment]
@paluchas @yf508 @RKasprowicz 

Rowena and I have some search questions (for once it's working)
Will it search multiple terms i.e. AND e.g. if someone types "French English" will it search for French AND English. If someone wants to type in multiple terms should they use a comma?
Also, if someone searches "explicit" will it pull out "explicit instruction" and "explicit knowledge" for example? i.e. partial hits.

**Comment by paluchas** [comment]
@SophieThompson @SophieThompson All title and facets labels are searchable as free text from the box now.

From my brief search it looks like entering more than one terms will bring all summaries with at least one term so this is like OR.

**Comment by SophieThompson** [comment]
This seems ok to me. I've tried terms already used, terms in the DD but not used, and nonsense words and all seem to work, so do multiple terms.

The only thing I noticed is that if I enter French German then both terms are searched for i.e. OR search, but when I include a spelling mistake (see below) nothing comes up, so French isn’t recognised. I’m logging this as it’s worth knowing about the nature of the search, I don’t know if this is an issue? Do you think it is @RKasprowicz 
![image](https://user-images.githubusercontent.com/36706240/37356889-ebc782c6-26de-11e8-8d38-f02c027de070.png)

**Comment by RKasprowicz** [comment]
@SophieThompson If you insert a comma between the words, does it search them "separately"? i.e. find a result for French but not German as it's spelt incorrectly?

**Comment by SophieThompson** [comment]
@RKasprowicz No it still doesn't work...

![image](https://user-images.githubusercontent.com/36706240/37394303-5165a48c-276b-11e8-9fa3-d047c7fa000f.png)

**Comment by RKasprowicz** [comment]
@paluchas @yf508 @SophieThompson Frank, Sebastian, please see Sophie's comments above about the free text search. The search function seems to work ok if the user enters a term, exactly as it appears in the DD. This is ok for now, but longer term / for the next phase, the search will need to be more 'intelligent' if possible. For example, if the user searches "French, Germa" the search should bring up the results for French, even though German is spelt incorrectly. 

@paluchas @yf508 Is the free search box able to cope with multiple terms at one time, or does the search read whatever is entered in the search box as a single term? (e.g. if I entered "grammar vocabulary", does the system search for the single term "grammar vocabulary" or will it search for "grammar" and "vocabulary" separately?

**Comment by yf508** [comment]
@RKasprowicz the system should search any words you entered separately, e.g. if you enter 'grammar vocabulary' in the search box, it should search for 'grammar' OR 'vocabulary'. I've checked the underlying search engine configuration but couldn't find the answer. I would leave it for now and logged this issue as a bug #102

**Comment by paluchas** [comment]
I'm closing this at this stage and we will explore better search in a future System iteration.
