### ISSUE TITLE
Search results page: Search terms under "Gender of learners" not displaying correctly

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#69]
The terms "Mixed" and "Female" are displaying. But there are three separate numbers given so should "Male" appear too?

![image](https://user-images.githubusercontent.com/36402489/37090673-21b2ce9a-21fd-11e8-9533-bba4f3a2b1eb.png)

**Comment by RKasprowicz** [comment]
see #55

**Comment by SophieThompson** [comment]
Have checked this again and still not showing correctly, although now the 7 summaries are showing as below: 

![image](https://user-images.githubusercontent.com/36706240/37161238-086f9420-22ea-11e8-89a8-9cf1b7ea5723.png)

**Comment by yf508** [comment]
As explained in #76 , this issue should be fixed when we have cleaned data on demo/live site.

**Comment by paluchas** [comment]
Yeh, I have pruned some old records and this is ok now.

**Comment by RKasprowicz** [comment]
@paluchas I agree. This bug is now fixed.
