### ISSUE TITLE
Search facets appearing non-alphabetical / correctly

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#73]
The search labels do not appear in alphabetical order in the dropdown menus. This is an issue for all the search categories (see below) e.g. Language being learnered > English, French, Arabic, English (English is duplicated too)

So two issues - alphabetical order and duplicate labels.

![image](https://user-images.githubusercontent.com/36706240/37161840-a8dba72c-22eb-11e8-8cd0-1736ba8e5014.png)

**Comment by RKasprowicz** [comment]
This is no longer an issue. Terms appear according to how many times they have been used to tag summaries. We are happy with this.
