### ISSUE TITLE
Search results page: Cross-linguistic influence listed twice under "Topic"

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#74]
The term "Cross-linguistic influence" is listed in two places under "Topic". Each term should only appear once, with the number on the right-hand side indicating how many summaries are tagged with this term.

![image](https://user-images.githubusercontent.com/36402489/37162016-1e03a766-22ec-11e8-992c-28cd7ec787b0.png)

**Comment by paluchas** [comment]
Related to an old metadata record. Once corrected this show ok.

**Comment by RKasprowicz** [comment]
@paluchas I agree. This issue has been fixed.
