### ISSUE TITLE
Search results page: Incorrect terms in "Participant type" search facet

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#75]
1. The terms "adult learners" "young learners" "adolescent learners" "primary school" need to be removed from the "Participant type" category (related to  #68 and #45).

![image](https://user-images.githubusercontent.com/36402489/37162174-7f754c16-22ec-11e8-89ed-fb86d94b3739.png)

2. The term L1 needs to be removed - this is not included in the list of "Participant type" terms (it is not in the list on the upload form either), so I am not sure why it is displaying here?

![image](https://user-images.githubusercontent.com/36402489/37162208-9317f57a-22ec-11e8-9fd6-374c75acafcd.png)

**Comment by paluchas** [comment]
Once old records have been removed I can't see the wrong values in this facet list.

**Comment by RKasprowicz** [comment]
@paluchas I agree. This issue has been fixed.
