### ISSUE TITLE
Update language being learned and first language of learners 

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#79]
@yf508 The list of languages in IRIS is much longer than the list we have (see below)? First language and Language being learned are not in the data dictionary in IRIS so we couldn't copy the full list across to use on OASIS. Where does the list of languages in IRIS come from? And can we use the same list in OASIS for language being learned and first language of learners? 

![image](https://user-images.githubusercontent.com/36706240/37164622-be3e9eba-22f2-11e8-8a7b-17292405cb70.png)

**Comment by paluchas** [comment]
it will be resolved by #

**Comment by yf508** [comment]
updated from IRIS language list.
