### ISSUE TITLE
Hyrax edit form won't work with checkbox forms

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#81]
Seen through issues #53, #61. We had to revert use of checkboxes at #56. We still have an issue with terms and conditions checkbox, however, this is also related to the missing configuration at [build_permit_params](https://github.com/digital-york/oasis/commit/19d44d124c0f20e5ca106cfed980527b6c7eb854) (see related #70)

We probably have to report this upstream after further testing.

**Comment by yf508** [comment]
The root cause for this problem is because simple form cannot properly deal with the string values from a collection.
