### ISSUE TITLE
NoMethodError in Hyrax::Admin::Workflows#index bug

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#82]
On our demo with this last rebase commit 71524a07099ed500acd98addc4994f8e98e19b17 I have notied the following raisl error

```
NoMethodError in Hyrax::Admin::Workflows#index
Showing /usr/local/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hyrax-2.0.1/app/views/hyrax/admin/workflows/index.html.erb where line #71 raised:

undefined method `empty?' for nil:NilClass

Extracted source (around line #225):
```

To reproduce error simply log in as admin -> dashboard -> select Review Submissions from TASKS left menu section. 

This error doesn't show at our current production with this last commit 5f7b8d779e6a38f554fe5faca3744ea486c9ec0e

Unfortunately, it looks that the error was introduced in between those two commits.

**Comment by paluchas** [comment]
The issue replicates on the system with data. The master branch with #60 merge has the bug already.

**Comment by yf508** [comment]
fixed
