### ISSUE TITLE
Text on homepage under search bar

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#84]
We need to remove the text "Leave the search bar empty and click "Go" to view all content....etc."

And replace with: "Click on "All Summaries" to view all content on OASIS and then use the filters to refine your search"

![image](https://user-images.githubusercontent.com/36706240/37290576-82db2b4e-2604-11e8-99f9-cd1dbae71dee.png)

**Comment by yf508** [comment]
done and will be on demo/live after next update.
