### ISSUE TITLE
Temporarily hide login link

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#86]
This is a temporary measure before a correct deposit process is not confirmed by OASIS. It should help to stop random users depositing and publishing summaries without editorial review.

**Comment by yf508** [comment]
done.

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson This is applied to the demo site. Bookmark the following links for your reference.

https://dlibingdev0.york.ac.uk/users/sign_in?locale=en
https://oasis-database.org/users/sign_in?locale=en
