### ISSUE TITLE
Change background colour of logo to white

### ISSUE THREAD

**Issue by paluchas** [digital-york/oasis#87]

**Comment by Jimadine** [comment]
Fixed in abeed21539ef3b6a48e1ba23e2084855d5ca77d5

**Comment by paluchas** [comment]
@RKasprowicz @SophieThompson demo server no contains this change #99. This should resolve this issue.

**Comment by SophieThompson** [comment]
Yes, this looks good now. @RKasprowicz if you also think it's ok then this issue can be closed.

**Comment by RKasprowicz** [comment]
@paluchas I've looked at the screenshot you have provided on #99. This looks good (I can't access the demo site at the moment as I'm not on the uni network at the moment). I'm happy for this to be pushed live.
