### ISSUE TITLE
Spacing problem with date in "publication" field

### ISSUE THREAD

**Issue by SophieThompson** [digital-york/oasis#89]
@paluchas @yf508 I've just uploaded two new summaries. One has a space missing between the second author and date i.e. Rosano(1993), the other is fine. Not sure why this would have happened, a bug perhaps?

As an aside, I deleted the other summaries 30 mins ago but they're still appearing on the "all summaries" page and in the recently uploaded. (I've logged out and back in again and they're still there)

![image](https://user-images.githubusercontent.com/36706240/37297932-e15cd692-2616-11e8-8e5e-0b39efd90f92.png)

**Comment by yf508** [comment]
fixed and will be ready for test after next update on dev
