### ISSUE TITLE
Search results page: Publication information appearing in two different formats

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#96]
The information in "Publication" field is not appearing in a consistent format on the search results page.

In some, authors surname and initial is included, and individual authors are separated by a semi-colon, as below:
![image](https://user-images.githubusercontent.com/36402489/37352773-e7dc25da-26d5-11e8-80cd-c3739620bb7d.png)

In others, authors surname only (no initial) appears and authors are separated by &, as below:
![image](https://user-images.githubusercontent.com/36402489/37352850-0c1b4f8e-26d6-11e8-8506-6dedf6f49f55.png)

**Comment by RKasprowicz** [comment]
@yf508 @paluchas I believe this issue is due to the temporary fix #29 for original issue #32

**Comment by paluchas** [comment]
@RKasprowicz correct, this is down to metadata entry in the additional all authors field.
