### ISSUE TITLE
Upload form: name of metadata field "Publication author all" needs to be updated

### ISSUE THREAD

**Issue by RKasprowicz** [digital-york/oasis#97]
Please update name of metadata field "Publication author all" --> "All authors of publication".

Please add the following description under the "All authors of publication" field heading:
Please list all authors of the publication in APA format (e.g. Surname, initial., Surname, initial. & Surname, initial.)

Please add the following description under the "All writers of summary" field heading:
Please list all writers of the summary in APA format (e.g. Surname, initial., Surname, initial. & Surname, initial.)

**Comment by yf508** [comment]
done
